#ifndef SOUND_SHARED_H
#define SOUND_SHARED_H

#include <QAudioFormat>
#include <QSysInfo>
#include <AL/al.h>
#include <AL/alc.h>
#include <AL/alext.h>
#include <exception>

static const QAudioFormat::Endian g_sys_endian
 = (QSysInfo::ByteOrder == QSysInfo::LittleEndian) ? QAudioFormat::LittleEndian
												   : QAudioFormat::BigEndian;

enum {
	MAX_SOURCE_SFX = 1
};

enum SoundEffect {
	SFX_REVERB_PRESET_GENERIC = 0,
	SFX_REVERB_PRESET_PADDEDCELL,
	SFX_REVERB_PRESET_ROOM,
	SFX_REVERB_PRESET_BATHROOM,
	SFX_REVERB_PRESET_LIVINGROOM,
	SFX_REVERB_PRESET_STONEROOM,
	SFX_REVERB_PRESET_AUDITORIUM,
	SFX_REVERB_PRESET_CONCERTHALL,
	SFX_REVERB_PRESET_CAVE,
	SFX_REVERB_PRESET_ARENA,
	SFX_REVERB_PRESET_HANGAR,
	SFX_REVERB_PRESET_CARPETEDHALLWAY,
	SFX_REVERB_PRESET_HALLWAY,
	SFX_REVERB_PRESET_STONECORRIDOR,
	SFX_REVERB_PRESET_ALLEY,
	SFX_REVERB_PRESET_FOREST,
	SFX_REVERB_PRESET_CITY,
	SFX_REVERB_PRESET_MOUNTAINS,
	SFX_REVERB_PRESET_QUARRY,
	SFX_REVERB_PRESET_PLAIN,
	SFX_REVERB_PRESET_PARKINGLOT,
	SFX_REVERB_PRESET_SEWERPIPE,
	SFX_REVERB_PRESET_UNDERWATER,
	SFX_REVERB_PRESET_DRUGGED,
	SFX_REVERB_PRESET_DIZZY,
	SFX_REVERB_PRESET_PSYCHOTIC,
	SFX_REVERB_PRESET_CASTLE_SMALLROOM,
	SFX_REVERB_PRESET_CASTLE_SHORTPASSAGE,
	SFX_REVERB_PRESET_CASTLE_MEDIUMROOM,
	SFX_REVERB_PRESET_CASTLE_LARGEROOM,
	SFX_REVERB_PRESET_CASTLE_LONGPASSAGE,
	SFX_REVERB_PRESET_CASTLE_HALL,
	SFX_REVERB_PRESET_CASTLE_CUPBOARD,
	SFX_REVERB_PRESET_CASTLE_COURTYARD,
	SFX_REVERB_PRESET_CASTLE_ALCOVE,
	SFX_REVERB_PRESET_FACTORY_SMALLROOM,
	SFX_REVERB_PRESET_FACTORY_SHORTPASSAGE,
	SFX_REVERB_PRESET_FACTORY_MEDIUMROOM,
	SFX_REVERB_PRESET_FACTORY_LARGEROOM,
	SFX_REVERB_PRESET_FACTORY_LONGPASSAGE,
	SFX_REVERB_PRESET_FACTORY_HALL,
	SFX_REVERB_PRESET_FACTORY_CUPBOARD,
	SFX_REVERB_PRESET_FACTORY_COURTYARD,
	SFX_REVERB_PRESET_FACTORY_ALCOVE,
	SFX_REVERB_PRESET_ICEPALACE_SMALLROOM,
	SFX_REVERB_PRESET_ICEPALACE_SHORTPASSAGE,
	SFX_REVERB_PRESET_ICEPALACE_MEDIUMROOM,
	SFX_REVERB_PRESET_ICEPALACE_LARGEROOM,
	SFX_REVERB_PRESET_ICEPALACE_LONGPASSAGE,
	SFX_REVERB_PRESET_ICEPALACE_HALL,
	SFX_REVERB_PRESET_ICEPALACE_CUPBOARD,
	SFX_REVERB_PRESET_ICEPALACE_COURTYARD,
	SFX_REVERB_PRESET_ICEPALACE_ALCOVE,
	SFX_REVERB_PRESET_SPACESTATION_SMALLROOM,
	SFX_REVERB_PRESET_SPACESTATION_SHORTPASSAGE,
	SFX_REVERB_PRESET_SPACESTATION_MEDIUMROOM,
	SFX_REVERB_PRESET_SPACESTATION_LARGEROOM,
	SFX_REVERB_PRESET_SPACESTATION_LONGPASSAGE,
	SFX_REVERB_PRESET_SPACESTATION_HALL,
	SFX_REVERB_PRESET_SPACESTATION_CUPBOARD,
	SFX_REVERB_PRESET_SPACESTATION_ALCOVE,
	SFX_REVERB_PRESET_WOODEN_SMALLROOM,
	SFX_REVERB_PRESET_WOODEN_SHORTPASSAGE,
	SFX_REVERB_PRESET_WOODEN_MEDIUMROOM,
	SFX_REVERB_PRESET_WOODEN_LARGEROOM,
	SFX_REVERB_PRESET_WOODEN_LONGPASSAGE,
	SFX_REVERB_PRESET_WOODEN_HALL,
	SFX_REVERB_PRESET_WOODEN_CUPBOARD,
	SFX_REVERB_PRESET_WOODEN_COURTYARD,
	SFX_REVERB_PRESET_WOODEN_ALCOVE,
	SFX_REVERB_PRESET_SPORT_EMPTYSTADIUM,
	SFX_REVERB_PRESET_SPORT_SQUASHCOURT,
	SFX_REVERB_PRESET_SPORT_SMALLSWIMMINGPOOL,
	SFX_REVERB_PRESET_SPORT_LARGESWIMMINGPOOL,
	SFX_REVERB_PRESET_SPORT_GYMNASIUM,
	SFX_REVERB_PRESET_SPORT_FULLSTADIUM,
	SFX_REVERB_PRESET_SPORT_STADIUMTANNOY,
	SFX_REVERB_PRESET_PREFAB_WORKSHOP,
	SFX_REVERB_PRESET_PREFAB_SCHOOLROOM,
	SFX_REVERB_PRESET_PREFAB_PRACTISEROOM,
	SFX_REVERB_PRESET_PREFAB_OUTHOUSE,
	SFX_REVERB_PRESET_PREFAB_CARAVAN,
	SFX_REVERB_PRESET_DOME_TOMB,
	SFX_REVERB_PRESET_PIPE_SMALL,
	SFX_REVERB_PRESET_DOME_SAINTPAULS,
	SFX_REVERB_PRESET_PIPE_LONGTHIN,
	SFX_REVERB_PRESET_PIPE_LARGE,
	SFX_REVERB_PRESET_PIPE_RESONANT,
	SFX_REVERB_PRESET_OUTDOORS_BACKYARD,
	SFX_REVERB_PRESET_OUTDOORS_ROLLINGPLAINS,
	SFX_REVERB_PRESET_OUTDOORS_DEEPCANYON,
	SFX_REVERB_PRESET_OUTDOORS_CREEK,
	SFX_REVERB_PRESET_OUTDOORS_VALLEY,
	SFX_REVERB_PRESET_MOOD_HEAVEN,
	SFX_REVERB_PRESET_MOOD_HELL,
	SFX_REVERB_PRESET_MOOD_MEMORY,
	SFX_REVERB_PRESET_DRIVING_COMMENTATOR,
	SFX_REVERB_PRESET_DRIVING_PITGARAGE,
	SFX_REVERB_PRESET_DRIVING_INCAR_RACER,
	SFX_REVERB_PRESET_DRIVING_INCAR_SPORTS,
	SFX_REVERB_PRESET_DRIVING_INCAR_LUXURY,
	SFX_REVERB_PRESET_DRIVING_FULLGRANDSTAND,
	SFX_REVERB_PRESET_DRIVING_EMPTYGRANDSTAND,
	SFX_REVERB_PRESET_DRIVING_TUNNEL,
	SFX_REVERB_PRESET_CITY_STREETS,
	SFX_REVERB_PRESET_CITY_SUBWAY,
	SFX_REVERB_PRESET_CITY_MUSEUM,
	SFX_REVERB_PRESET_CITY_LIBRARY,
	SFX_REVERB_PRESET_CITY_UNDERPASS,
	SFX_REVERB_PRESET_CITY_ABANDONED,
	SFX_REVERB_PRESET_DUSTYROOM,
	SFX_REVERB_PRESET_CHAPEL,
	SFX_REVERB_PRESET_SMALLWATERROOM,
	
	SFX_COUNT,
	SFX_DISABLED = SFX_COUNT
};

enum SoundFilter {
	SFE_NONE = 0,
	SFE_MUFFLE_1,
	SFE_MUFFLE_2,
	SFE_MUFFLE_3,
	SFE_MUFFLE_4,
	SFE_MUFFLE_5,
	SFE_MUFFLE_6,
	SFE_MUFFLE_7,
	SFE_MUFFLE_8,
	SFE_MUFFLE_9,
	SFE_MUFFLE_10,
	
	SFE_COUNT,
	SFE_DISABLED = SFE_COUNT
};

struct ExtensionProcs {
	LPALGENEFFECTS alGenEffects;
	LPALDELETEEFFECTS alDeleteEffects;
	LPALISEFFECT alIsEffect;
	LPALEFFECTI alEffecti;
	LPALEFFECTIV alEffectiv;
	LPALEFFECTF alEffectf;
	LPALEFFECTFV alEffectfv;
	LPALGETEFFECTI alGetEffecti;
	LPALGETEFFECTIV alGetEffectiv;
	LPALGETEFFECTF alGetEffectf;
	LPALGETEFFECTFV alGetEffectfv;
	
	LPALGENFILTERS alGenFilters;
	LPALDELETEFILTERS alDeleteFilters;
	LPALISFILTER alIsFilter;
	LPALFILTERI alFilteri;
	LPALFILTERIV alFilteriv;
	LPALFILTERF alFilterf;
	LPALFILTERFV alFilterfv;
	LPALGETFILTERI alGetFilteri;
	LPALGETFILTERIV alGetFilteriv;
	LPALGETFILTERF alGetFilterf;
	LPALGETFILTERFV alGetFilterfv;

	LPALGENAUXILIARYEFFECTSLOTS alGenAuxiliaryEffectSlots;
	LPALDELETEAUXILIARYEFFECTSLOTS alDeleteAuxiliaryEffectSlots;
	LPALISAUXILIARYEFFECTSLOT alIsAuxiliaryEffectSlot;
	LPALAUXILIARYEFFECTSLOTI alAuxiliaryEffectSloti;
	LPALAUXILIARYEFFECTSLOTIV alAuxiliaryEffectSlotiv;
	LPALAUXILIARYEFFECTSLOTF alAuxiliaryEffectSlotf;
	LPALAUXILIARYEFFECTSLOTFV alAuxiliaryEffectSlotfv;
	LPALGETAUXILIARYEFFECTSLOTI alGetAuxiliaryEffectSloti;
	LPALGETAUXILIARYEFFECTSLOTIV alGetAuxiliaryEffectSlotiv;
	LPALGETAUXILIARYEFFECTSLOTF alGetAuxiliaryEffectSlotf;
	LPALGETAUXILIARYEFFECTSLOTFV alGetAuxiliaryEffectSlotfv;
};

namespace Snd {
	void handleErrors();
	
	SoundEffect GetSoundEffectByName(QString const&);
	SoundFilter GetSoundFilterByName(QString const&);
}

#endif // SOUND_SHARED_H
